### ISSUE TITLE
geom_line_trace groups when using trace_position predicate

### ISSUE THREAD

**Issue by sheridar** [rnabioco/ggtrace#29]
* `geom_line()` needs groups so it knows how to draw each line
* groups get set when mapping variables to aesthetics (`color = variable`)
* when passing a predicate to trace_position, groups set by `color` are overwritten since the background layer by default is not outlined (`color = NA`)
* this does not affect `geom_point_trace()` since groups are not needed to correctly draw points

```r
# works
economics_long %>%
  ggplot(aes(date, value01, color = variable)) +
  geom_line_trace()

economics_long %>%
  ggplot(aes(date, value01, fill = variable)) +
  geom_line_trace(trace_position = variable == "pce")

# broken
economics_long %>%
  ggplot(aes(date, value01, color = variable)) +
  geom_line_trace(trace_position = variable == "pce")
```

**Comment by sheridar** [comment]
* Can fix by automatically adding groups when user maps variable to color.
* Otherwise user would always have to set groups within aes(), not ideal.

**Comment by jayhesselberth** [comment]
Can you just set the groups to all under the hood, unless a specific mapping is requested?
